/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1c1b1b",
        "on-tertiary-container": "#282930",
        "on-surface-variant": "#c7c4d7",
        "on-primary-fixed": "#07006c",
        "on-error": "#690005",
        "on-background": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "background": "#131313",
        "primary-fixed-dim": "#c0c1ff",
        "secondary": "#c6c6c7",
        "tertiary-fixed-dim": "#c6c6cf",
        "inverse-primary": "#494bd6",
        "surface-bright": "#3a3939",
        "on-secondary-container": "#b4b5b5",
        "tertiary-fixed": "#e2e1eb",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#1a1b22",
        "tertiary": "#c6c6cf",
        "primary": "#c0c1ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-surface": "#e5e2e1",
        "tertiary-container": "#909099",
        "on-primary-container": "#0d0096",
        "surface-variant": "#353534",
        "surface-tint": "#c0c1ff",
        "secondary-container": "#454747",
        "on-secondary": "#2f3131",
        "primary-fixed": "#e1e0ff",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary": "#1000a9",
        "error": "#ffb4ab",
        "outline": "#908fa0",
        "secondary-fixed-dim": "#c6c6c7",
        "surface-dim": "#131313",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#313030",
        "on-tertiary": "#2f3037",
        "surface": "#131313",
        "primary-container": "#8083ff",
        "surface-container": "#201f1f",
        "on-tertiary-fixed-variant": "#45464e",
        "on-surface": "#e5e2e1",
        "outline-variant": "#262626",
        "indigo-accent": "#6366f1",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "unit": "4px",
        "container-max": "1440px",
        "margin-desktop": "40px",
        "sidebar-width": "260px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-sm": ["Geist"],
        "display-lg": ["Geist"],
        "label-md": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
        "headline-md": ["Geist"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
